name: VarLight
version: "plugin.version"
author: shawlaf
main: me.shawlaf.varlight.VarLightPlugin
description: Turn Normal Blocks into Light Sources!
api-version: "api.version"

softdepend:
  - "Multiverse-Core"
  - "LightAPI"

permissions:
  varlight.admin:
    description: "Provides access to the varlight admin commands"
    default: op
    children:
      varlight.admin.debug: true
      varlight.admin.save: true
      varlight.admin.perm: true
      varlight.admin.world: true
