name: VarLight
version: "1.3"
author: Florian
main: me.florian.varlight.VarLightPlugin
description: Turn Normal Blocks into Light Sources!
api-version: "1.13"

softdepend:
  - LightAPI

commands:
  save-lights:
    description: Save all persisten lights to disk
    permission: varlight.admin
  set-permission:
    description: Update the required permission to place custom light sources
    permission: varlight.admin
    usage: /set-permission <node>
